### ISSUE TITLE
"erroneous constant encountered" when I pass an enum to endpoints! as Tx/Rx type

### ISSUE THREAD

**Issue by Dicklessgreat** [jamesmunns/postcard-rpc#57]
Today I updated postcard-rpc from 0.9 to the latest(0.10.6).
It worked fine on 0.9, but seems macro expansion failed in my case with latest one.
And it seems this error is caused by passing an `enum` with a variant that has any fields, to `endpoint!` or `topics!`.

You can reproduce the error:
```
#[derive(Schema)]
enum A {
    P(i32),
    Q
}
endpoints! {
    list = ENDPOINTS_LIST;
    omit_std = true;
    | EndpointTy   | RequestTy | ResponseTy | Path              |
    | ----------   | --------- | ---------- | ----              |
    | SomeEndpoint | A         | ()         | "path/some"       |
}

```
emits an error:
```
erroneous constant encountered
uniques.rs(672, 76): Actual error occurred here
macros.rs(102, 21): Error originated from macro call here
macros.rs(193, 20): Error originated from macro call here
```
build error message:
```
error[E0080]: evaluation of constant value failed
   --> /path/to/postcard-rpc/source/postcard-rpc/src/uniques.rs:379:9
    |
379 |         arr[used] = Some(nty);
    |         ^^^^^^^^^ index out of bounds: the length is 1 but the index is 1
    |
note: inside `type_chewer_nty::<1>`
   --> /path/to/postcard-rpc/source/postcard-rpc/src/uniques.rs:379:9
    |
379 |         arr[used] = Some(nty);
    |         ^^^^^^^^^
note: inside `ENDPOINTS_LIST::{constant#0}::LISTS::{constant#0}::BIG_RPT`
   --> src/icd.rs:28:1
    |
28  | / endpoints! {
29  | |     list = ENDPOINTS_LIST;
30  | |     omit_std = true;
31  | |     | EndpointTy   | RequestTy | ResponseTy | Path              |
32  | |     | ----------   | --------- | ---------- | ----              |
33  | |     | SomeEndpoint | A         | ()         | "path/some"       |
34  | | }
    | |_^
    = note: this error originates in the macro `$crate::unique_types` which comes from the expansion of the macro `endpoints` (in Nightly builds, run with -Z macro-backtrace for more info)

note: erroneous constant encountered
  --> src/icd.rs:28:1
   |
28 | / endpoints! {
29 | |     list = ENDPOINTS_LIST;
30 | |     omit_std = true;
31 | |     | EndpointTy   | RequestTy | ResponseTy | Path              |
32 | |     | ----------   | --------- | ---------- | ----              |
33 | |     | SomeEndpoint | A         | ()         | "path/some"       |
34 | | }
   | |_^
   |
   = note: this note originates in the macro `$crate::unique_types` which comes from the expansion of the macro `endpoints` (in Nightly builds, run with -Z macro-backtrace for more info)
```

- If `A` is at `ResponseTy` or `MessageTy`(in `topics!`), the same error emits. 
- If `A` has no variants with fields(like `enum A { P, Q }`), then it works fine

**Comment by jamesmunns** [comment]
Hey there @Dicklessgreat - I think I fixed this in https://github.com/jamesmunns/postcard-rpc/commit/ce636c3a285f9da4578f34fbe12afbb1ab0e7d3e, could you please check if `v0.10.7` works for you?

**Comment by Dicklessgreat** [comment]
Hi James!

Thank you for addressing this so quickly! I tested v0.10.7, and everything is working perfectly now.Your fix in ce636c3 resolved the issue on my end. I appreciate your efforts in getting this sorted out.

Thanks again! 😊
